apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-server
  namespace: nori-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-server
  template:
    metadata:
      labels:
        app: contacts-server
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: contacts-server
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "500m"
          image: ghcr.io/nori-group/nori-contacts-server:v0.1.2
          envFrom:
            - secretRef:
                name: contacts-server-secret
          ports:
            - containerPort: 80

