apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
  namespace: nori-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      automountServiceAccountToken: false
      initContainers:
        - name: synapse-config-generator
          image: ghcr.io/element-hq/synapse:v1.128.0 
          args: ["generate"]
          env:
            - name: SYNAPSE_SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  name: matrix-domain-config
                  key: main_domain
            - name: SYNAPSE_REPORT_STATS
              value: "no"
          volumeMounts:
          - name: synapse-data
            mountPath: /data
      containers:
        - name: synapse
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          image: ghcr.io/element-hq/synapse:v1.128.0
          env:
            - name: SYNAPSE_SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  name: matrix-domain-config
                  key: matrix_domain
            - name: SYNAPSE_REPORT_STATS
              value: "no"
            - name: SYNAPSE_CONFIG_PATH
              value: "/data/homeserver.yaml"
          ports:
            - containerPort: 8008
          volumeMounts:
            - name: synapse-data
              mountPath: /data
            - name: mautrix-telegram-data
              mountPath: /data/mautrix-telegram
      volumes:
      - name: synapse-data
        persistentVolumeClaim:
          claimName: synapse-pvc
      - name: mautrix-telegram-data
        persistentVolumeClaim:
          claimName: mautrix-telegram-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: synapse-config-editor
  namespace: nori-infra
spec:
  containers:
  - name: editor-container
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: synapse-data-volume
      mountPath: /data
  volumes:
  - name: synapse-data-volume
    persistentVolumeClaim:
      claimName: synapse-pvc