apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nori-infra
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  # change this password when deploying to production
  POSTGRES_PASSWORD: postgres